export const inclusions: string[] = [
  "Roundtrip land transfers (port ↔ accommodation)",
  "Roundtrip boat transfers (island hopping)",
  "Licensed local tour guide",
  "Island hopping to Virgin Island, Hilantagaan, Sandbar",
  "Environmental/docking fees",
  "Life vest and snorkeling gear",
  "Grilled lunch during island hopping",
  "Complimentary breakfast (with accommodation)",
  "Air-conditioned room accommodation",
  "Fan room accommodation",
  "Entrance fees to tourist sites",
  "Ogtong Cave / Paradise Beach access",
  "Kota Park & Madridejos Ruins visit",
  "Sts. Peter & Paul Parish visit",
  "Photo/video assistance from guide",
  "Free welcome drink or snacks",
  "Free souvenir item",
  "Tour coordinator support",
  "Travel insurance (if bundled)",
  "GoPro rental (if included)",
];

export const exclusions: string[] = [
  "Airfare (Cebu-bound flights)",
  "Ferry ticket (Hagnaya ↔ Bantayan)",
  "Meals not specified in the package",
  "Alcoholic beverages",
  "Tips and gratuities",
  "Personal shopping/souvenirs",
  "Room service or minibar charges",
  "Kayak/paddleboard/jet ski rental",
  "Cliff diving entrance fee",
  "Extra night stay/accommodation upgrades",
  "Drone or professional photography",
  "Travel insurance (if not bundled)",
  "Transportation outside of tour scope",
  "Entrance fees to optional destinations",
  "Environmental fees (if not covered)",
];
